basic:
    name: 'https://website.pixieset.com'
    environments:
        production: 'https://website.pixieset.com'
        staging: ''
        development: ''
    breakpoints:
        - 1024
    pages:
        - /
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { value: 'en-US,en;q=0.9', header: Accept-Language }
        - { value: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36', header: User-Agent }
        - { value: document, header: Sec-Fetch-Dest }
        - { value: navigate, header: Sec-Fetch-Mode }
        - { value: same-origin, header: Sec-Fetch-Site }
        - { value: '?1', header: Sec-Fetch-User }
        - { value: '1', header: Upgrade-Insecure-Requests }
        - { value: keep-alive, header: Connection }
        - { value: '1', header: DNT }
        - { value: max-age=0, header: Cache-Control }
        - { value: 'gzip, deflate, br', header: Accept-Encoding }
        - { value: '"Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"', header: Sec-CH-UA }
    cookies: ''
    custom_js: ''
    custom_css: "img {\n\theight: auto !important;\n}\n\nhtml, body, .page-container {\n  \theight: auto !important; \n    min-height: 100vh !important; \n}"
    mock_content:
        - { type: title, selector: '' }
    login:
        type: custom
        click_element: true
        click_element_selector: .ps-cookie-popup__button.ps-cookie-popup__button--allow
        login_url: '/login/?spId=website'
        username: ''
        password: ''
        username_selector: '#UserLogin_username'
        password_selector: '#UserLogin_password'
        submit_selector: '#login-button'
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
