basic:
    name: 'https://website.pixieset.com'
    environments:
        production: 'https://website.pixieset.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 760
        - 768
        - 1024
        - 1080
        - 1200
        - 1920
    pages:
        - /
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { value: '', header: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { type: title, selector: '' }
    login:
        type: custom
        click_element: false
        click_element_selector: .header-login
        login_url: /login
        username: ''
        password: ''
        username_selector: '#UserLogin_username'
        password_selector: '#UserLogin_password'
        submit_selector: '#login-button'
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
