basic:
    name: 'https://website.pixieset.com'
    environments:
        production: 'https://website.pixieset.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 760
        - 768
        - 1024
        - 1080
        - 1200
        - 1920
    pages:
        - /
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { value: 'en-US,en;q=0.9', header: Accept-Language }
        - { value: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36', header: User-Agent }
        - { value: document, header: Sec-Fetch-Dest }
        - { value: navigate, header: Sec-Fetch-Mode }
        - { value: same-origin, header: Sec-Fetch-Site }
        - { value: '?1', header: Sec-Fetch-User }
        - { value: '1', header: Upgrade-Insecure-Requests }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { type: title, selector: '' }
    sensitivity: 15
    night_mode: false
    retina_images: false
    login:
        type: custom
        click_element: true
        click_element_selector: .ps-cookie-popup__button.ps-cookie-popup__button--allow
        login_url: 'https://accounts.pixieset.com/login/?spId=website'
        username: ''
        password: ''
        username_selector: '#UserLogin_username'
        password_selector: '#UserLogin_password'
        submit_selector: '#login-button'
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
proxy: true
type: single_site
